#!/bin/sh
# This script is only used for developement. It is removed by the
# distribution process.

set -e

OCAMLBUILD=${OCAMLBUILD:="ocamlbuild -tag debug -classic-display \
                          -use-ocamlfind -cflags -warn-error,+A" }

action ()
{
    case $1 in
        default) action lib ; action lwt ;;
        lwt) $OCAMLBUILD -I src logs-syslog-lwt.cma logs-syslog-lwt.cmxa  ;;
        lib) $OCAMLBUILD -I src logs-syslog.cma logs-syslog.cmxa logs-syslog-unix.cma logs-syslog-unix.cmxa ;;
        clean) $OCAMLBUILD -clean ;;
        *) $OCAMLBUILD $* ;;
    esac
}

if [ $# -eq 0 ];
then action default ;
else action $*; fi
